---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: docs/index.md
  label: Homepage
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: docs/articles
  label: Articles
  create: all
  match: "**/*"
  new_doc_ext: ".md"
- type: directory
  path: docs/toolsAndApps
  label: Tools and Apps
  create: all
  match: "**/*"
  new_doc_ext: ".md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
