---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Landing Pages
- type: document
  path: docs/index.md
  label: Homepage
- type: heading
  label: Content
- type: directory
  path: docs/articles
  label: Article
  create: all
  match: "**/*"
  new_doc_ext: md
- type: directory
  path: docs/toolsAndApps
  label: Tool or App
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: docs/.vuepress/public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
